### ISSUE TITLE
feature: support dynamic prompt wildcards in input fields

### ISSUE THREAD

**Issue by neverwill-net** [AUTOMATIC1111/stable-diffusion-webui-extensions#140]
Please add dynamic prompt wildcard realization support in this plugin's prompt field

**Comment by w-e-w** [comment]
I don't understand what you're saying
can you be more specific?

**Comment by neverwill-net** [comment]
Sorry I should have done a better job. I'm referring to wildcard variable expansion for this extension: 

https://github.com/adieyal/sd-dynamic-prompts

So we can use our existing wildcards in the if_ai_sd_mkr input fields

**Comment by w-e-w** [comment]
so you are requesting a feature of web UI???
https://github.com/adieyal/sd-dynamic-prompts
you want to use sd-dynamic-prompts extension ? well then then install it and use it use it?

or are you asking sd-dynamic-prompts to be included by default in as a built-in extension in webui?

in case you haven't noticed, you might be in the wrong repository to ask this
stable-diffusion-webui-**extensions** a repo for collecting extension delivered it as a index so that it can be easily found by users of web UI
and sd-dynamic-prompts has already been added to the index
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/blob/extensions/extensions/sd-dynamic-prompts.json

**Comment by neverwill-net** [comment]
No I'm asking for your plugin's ui fields prompt inputs to support expanding any dynamic prompt wildcards.

**Comment by w-e-w** [comment]
are you asking you categorization category?

**Comment by w-e-w** [comment]
![image](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/assets/40751091/8b8c7144-1e82-47d3-92fd-1a0ecc4baab0)

**Comment by w-e-w** [comment]
@neverwill-net 
I don't know how SD Dynamic prompts work but I would assume that it involved hooking into one of the callbacks and rewriting the prompts based on certain syntax
a different extension is executed after sd-dynamic-prompts then sd-dynamic-prompts cannot affect it

if I recall correctly if multiple extensions using the same callback then they are ordered alphabetically (base on the name of the clone folder)
this is kind of problematic but it's the system we're have now, they have been talks of implementing a proper system that let extensions declare explicitly their priority but it is not in web UI yet

for now if you with the change the execution order you should change the alphabetical order

if you're talking about having it apply to other text box not only the main text box
again most likely you have to modify or request a modification to be made on sd-dynamic-prompts

either way I interpreted you are asking in the wrong place
does this answer your question?
